# Generated by Django 4.2.7 on 2023-11-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
