# Generated by Django 4.2.7 on 2023-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_product_warehouse_delete_car_delete_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.TextField(default='Unfulfilled'),
        ),
    ]
